apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demov1-deployment
spec:
  selector:
    matchLabels:
      run: demov1-deployment
  replicas: 5
  template:
    metadata:
      labels:
        run: demov1-deployment
    spec:
      containers:
      - name: demov1-container
        image: sivasunku/demo.v1:latest
        ports:
        - containerPort: 80
