pipeline {
    agent { docker { image 'maven:3.3.3' } }
    // agent - none
    // agent { docker { image 'python:3.5.1' } }
    stages {
        stage('build') {
            steps {
                sh 'mvn --version'
                sh 'mvn compile'
            }
        }
    }
}
