
pipeline {
  agent any
  stages {
    //Stage for Code checkout from git  
    stage('CodeCheckout') {
      steps {
	    script {
		  checkout scm
		}
      }
   	} /* code checkout ends */
	
	/*This will get a Python image and build the new docker image */
	stage('Python Build') {
      steps {
	    script {
		  checkout scm
		}
      }
   	} /* Python Build ends */
  	
	stage('Docker Integration to Hub') {
      steps {
	    script {
		  sh 'sudo docker build -t sivasunku/demo.v1 .'
		  /*sh "docker login --username=$env.username --password=$env.password"*/
		  sh 'docker push sivasunku/demo.v1'
		}
      }
   	} /* Docker build and integration Ends */
	
	stage('Deploy to K8') {
/*      steps {
	  kubernetesDeploy (
        kubeconfigId: 'kubeconfig',
        configs: 'application.yaml',
        enableConfigSubstitution: false
        )
      } */
      steps {
        sh 'kubectl apply -f ./deployment.yaml'
        sh 'kubectl apply -f ./service.yaml'
      }
    } /* Kubernetes ends */
 
    }//stages ends here
}//pipeline ends here
