pipeline {
    // agent { docker { image 'maven:3.3.3' } }
    agent any
    // agent { docker { image 'python:3.5.1' } }
    stages {
        stage('build') {
            steps {
                cd 'java-source'
                sh 'mvn compile'
            }
        }
    }
}
